apiVersion: v1
data:
  client.crt: {{ .Values.temporal.tls.cert | b64enc | quote }}
  client.key: {{ .Values.temporal.tls.key | b64enc | quote }}
kind: Secret
metadata:
  creationTimestamp: null
  name: mtls-certs
  namespace: {{ .Release.Namespace }}